import { format, subDays } from 'date-fns'
import type { Patient, Visit, Invoice, Doctor, ChargePreset, LineItem } from '../types'

const today = format(new Date(), 'yyyy-MM-dd')
const yesterday = format(subDays(new Date(), 1), 'yyyy-MM-dd')
const twoDaysAgo = format(subDays(new Date(), 2), 'yyyy-MM-dd')

export const mockDoctors: Doctor[] = [
  { id: 'd1', name: 'Dr. Rakesh Sharma', specialization: 'General Physician', is_active: true },
  { id: 'd2', name: 'Dr. Priya Mehta', specialization: 'Pediatrician', is_active: true },
  { id: 'd3', name: 'Dr. Arjun Patel', specialization: 'Cardiologist', is_active: true },
  { id: 'd4', name: 'Dr. Sunita Rao', specialization: 'Dermatologist', is_active: false },
]

export const mockChargePresets: ChargePreset[] = [
  { id: 'cp1', name: 'Consultation Fee', amount: 300, category: 'consultation', is_active: true },
  { id: 'cp2', name: 'Follow-up Consultation', amount: 150, category: 'consultation', is_active: true },
  { id: 'cp3', name: 'Blood Test (CBC)', amount: 150, category: 'lab', is_active: true },
  { id: 'cp4', name: 'Blood Sugar Test', amount: 80, category: 'lab', is_active: true },
  { id: 'cp5', name: 'Urine Test', amount: 60, category: 'lab', is_active: true },
  { id: 'cp6', name: 'X-Ray', amount: 200, category: 'radiology', is_active: true },
  { id: 'cp7', name: 'ECG', amount: 150, category: 'diagnostic', is_active: true },
  { id: 'cp8', name: 'Dressing / Wound Care', amount: 100, category: 'procedure', is_active: true },
  { id: 'cp9', name: 'Injection / IV', amount: 50, category: 'procedure', is_active: true },
  { id: 'cp10', name: 'Ultrasound', amount: 400, category: 'radiology', is_active: true },
]

export const mockPatients: Patient[] = [
  {
    id: 'p1',
    full_name: 'Amit Kumar',
    age: 34,
    gender: 'male',
    phone: '9876543210',
    address: '12 Gandhi Nagar, Sector 5, Delhi',
    father_name: null,
    referral_source: null,
    blood_group: 'O+',
    created_at: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: 'p2',
    full_name: 'Priya Sharma',
    age: 28,
    gender: 'female',
    phone: '9765432109',
    address: '45 Shivaji Colony, Mumbai',
    father_name: null,
    referral_source: null,
    blood_group: 'A+',
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
  },
  {
    id: 'p3',
    full_name: 'Rajesh Verma',
    age: 52,
    gender: 'male',
    phone: '9654321098',
    address: 'Plot 8, Rajiv Nagar, Pune',
    father_name: null,
    referral_source: null,
    blood_group: 'B+',
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
  },
  {
    id: 'p4',
    full_name: 'Sunita Devi',
    age: 45,
    gender: 'female',
    phone: '9543210987',
    address: '78 Lake View Apartments, Hyderabad',
    father_name: null,
    referral_source: null,
    blood_group: 'AB+',
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
  },
  {
    id: 'p5',
    full_name: 'Mohammed Aslam',
    age: 61,
    gender: 'male',
    phone: '9432109876',
    address: '23 Bandra West, Mumbai',
    father_name: null,
    referral_source: null,
    blood_group: 'O-',
    created_at: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
  },
  {
    id: 'p6',
    full_name: 'Kavitha Nair',
    age: 19,
    gender: 'female',
    phone: '9321098765',
    address: '56 Marine Drive, Kochi',
    father_name: null,
    referral_source: null,
    blood_group: 'A-',
    created_at: new Date(Date.now() - 1000 * 60 * 180).toISOString(),
  },
  {
    id: 'p7',
    full_name: 'Deepak Singh',
    age: 38,
    gender: 'male',
    phone: '9210987654',
    address: '34 Civil Lines, Lucknow',
    father_name: null,
    referral_source: null,
    blood_group: 'B-',
    created_at: subDays(new Date(), 1).toISOString(),
  },
  {
    id: 'p8',
    full_name: 'Ananya Bose',
    age: 24,
    gender: 'female',
    phone: '9109876543',
    address: '90 Salt Lake, Kolkata',
    father_name: null,
    referral_source: null,
    blood_group: 'AB-',
    created_at: subDays(new Date(), 2).toISOString(),
  },
]

export const mockVisits: Visit[] = [
  {
    id: 'v1',
    patient_id: 'p1',
    doctor_id: 'd1',
    token_number: 1,
    token_date: today,
    consultation_date: today,
    consultation_time: '10:00',
    visit_type: 'first_visit',
    chief_complaint: 'Fever and cold for 3 days',
    status: 'completed',
    notes: 'Patient has mild fever 99.5°F. Advised rest and fluids.',
    prescription: 'Paracetamol 500mg TID x 3 days\nCetirizine 10mg OD x 5 days\nVit C 500mg OD x 7 days',
    registered_by: 'self',
    payment_method: 'cash',
    payment_method_locked_at: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    payment_method_override_by: null,
    payment_method_override_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 150).toISOString(),
    patient: mockPatients[0],
    doctor: mockDoctors[0],
  },
  {
    id: 'v2',
    patient_id: 'p2',
    doctor_id: 'd1',
    token_number: 2,
    token_date: today,
    consultation_date: today,
    consultation_time: '10:00',
    visit_type: 'first_visit',
    chief_complaint: 'Headache and dizziness',
    status: 'completed',
    notes: 'BP: 130/85. Advised lifestyle modification.',
    prescription: 'Amlodipine 5mg OD\nMetoprolol 25mg BD',
    registered_by: 'receptionist',
    payment_method: 'online',
    payment_method_locked_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    payment_method_override_by: null,
    payment_method_override_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 120).toISOString(),
    patient: mockPatients[1],
    doctor: mockDoctors[0],
  },
  {
    id: 'v3',
    patient_id: 'p3',
    doctor_id: 'd3',
    token_number: 3,
    token_date: today,
    consultation_date: today,
    consultation_time: '10:00',
    visit_type: 'first_visit',
    chief_complaint: 'Chest pain on exertion',
    status: 'pending',
    notes: null,
    prescription: null,
    registered_by: 'self',
    payment_method: 'cash',
    payment_method_locked_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    payment_method_override_by: null,
    payment_method_override_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    patient: mockPatients[2],
    doctor: mockDoctors[2],
  },
  {
    id: 'v4',
    patient_id: 'p4',
    doctor_id: 'd1',
    token_number: 4,
    token_date: today,
    consultation_date: today,
    consultation_time: '10:00',
    visit_type: 'first_visit',
    chief_complaint: 'Knee pain and swelling',
    status: 'pending',
    notes: null,
    prescription: null,
    registered_by: 'self',
    payment_method: 'online',
    payment_method_locked_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    payment_method_override_by: null,
    payment_method_override_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 60).toISOString(),
    patient: mockPatients[3],
    doctor: mockDoctors[0],
  },
  {
    id: 'v5',
    patient_id: 'p5',
    doctor_id: 'd3',
    token_number: 5,
    token_date: today,
    consultation_date: today,
    consultation_time: '10:00',
    visit_type: 'first_visit',
    chief_complaint: 'Routine cardiac checkup',
    status: 'pending',
    notes: null,
    prescription: null,
    registered_by: 'self',
    payment_method: 'cash',
    payment_method_locked_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    payment_method_override_by: null,
    payment_method_override_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 45).toISOString(),
    patient: mockPatients[4],
    doctor: mockDoctors[2],
  },
  {
    id: 'v6',
    patient_id: 'p6',
    doctor_id: 'd2',
    token_number: 6,
    token_date: today,
    consultation_date: today,
    consultation_time: '10:00',
    visit_type: 'first_visit',
    chief_complaint: 'Skin rash and itching',
    status: 'pending',
    notes: null,
    prescription: null,
    registered_by: 'self',
    payment_method: 'online',
    payment_method_locked_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    payment_method_override_by: null,
    payment_method_override_reason: null,
    created_at: new Date(Date.now() - 1000 * 60 * 20).toISOString(),
    patient: mockPatients[5],
    doctor: mockDoctors[1],
  },
  // Yesterday's visits
  {
    id: 'v7',
    patient_id: 'p7',
    doctor_id: 'd1',
    token_number: 1,
    token_date: yesterday,
    consultation_date: yesterday,
    consultation_time: '10:00',
    visit_type: 'first_visit',
    chief_complaint: 'Back pain for 2 weeks',
    status: 'completed',
    notes: 'Muscle spasm. Advised physiotherapy.',
    prescription: 'Diclofenac 50mg BD x 5 days\nMethocarbamol 500mg TID x 5 days',
    registered_by: 'receptionist',
    payment_method: 'cash',
    payment_method_locked_at: subDays(new Date(), 1).toISOString(),
    payment_method_override_by: null,
    payment_method_override_reason: null,
    created_at: subDays(new Date(), 1).toISOString(),
    patient: mockPatients[6],
    doctor: mockDoctors[0],
  },
  {
    id: 'v8',
    patient_id: 'p8',
    doctor_id: 'd2',
    token_number: 2,
    token_date: yesterday,
    consultation_date: yesterday,
    consultation_time: '10:00',
    visit_type: 'first_visit',
    chief_complaint: 'Stomach ache and nausea',
    status: 'completed',
    notes: 'Gastritis. Advised bland diet.',
    prescription: 'Omeprazole 20mg BD x 7 days\nDomperidone 10mg TID x 3 days',
    registered_by: 'self',
    payment_method: 'online',
    payment_method_locked_at: subDays(new Date(), 1).toISOString(),
    payment_method_override_by: null,
    payment_method_override_reason: null,
    created_at: subDays(new Date(), 1).toISOString(),
    patient: mockPatients[7],
    doctor: mockDoctors[1],
  },
  // Two days ago
  {
    id: 'v9',
    patient_id: 'p1',
    doctor_id: 'd1',
    token_number: 1,
    token_date: twoDaysAgo,
    consultation_date: twoDaysAgo,
    consultation_time: '10:00',
    visit_type: 'first_visit',
    chief_complaint: 'Follow-up visit',
    status: 'completed',
    notes: 'Improved. Continue medication.',
    prescription: null,
    registered_by: 'receptionist',
    payment_method: 'cash',
    payment_method_locked_at: subDays(new Date(), 2).toISOString(),
    payment_method_override_by: null,
    payment_method_override_reason: null,
    created_at: subDays(new Date(), 2).toISOString(),
    patient: mockPatients[0],
    doctor: mockDoctors[0],
  },
]

const makeInvoice = (
  id: string,
  visitId: string,
  patientId: string,
  invoiceNumber: string,
  items: LineItem[],
  discount: number,
  paymentStatus: 'pending' | 'paid_cash' | 'paid_online',
  paymentMethod: 'cash' | 'online_upi' | null,
  createdAt: string,
  paidAt: string | null,
  visit?: Visit,
  patient?: Patient
): Invoice => {
  const subtotal = items.reduce((acc, item) => acc + item.amount * item.quantity, 0)
  const total = subtotal - discount
  return {
    id,
    visit_id: visitId,
    patient_id: patientId,
    invoice_number: invoiceNumber,
    line_items: items,
    subtotal,
    discount,
    total,
    payment_status: paymentStatus,
    payment_method: paymentMethod,
    paid_at: paidAt,
    created_at: createdAt,
    visit,
    patient,
  }
}

export const mockInvoices: Invoice[] = [
  makeInvoice(
    'inv1', 'v1', 'p1', `${format(new Date(), 'yy')}${format(new Date(), 'MM')}-0001`,
    [
      { id: 'li1', name: 'Consultation Fee', quantity: 1, amount: 300 },
      { id: 'li2', name: 'Blood Test (CBC)', quantity: 1, amount: 150 },
    ],
    0, 'paid_cash', 'cash',
    new Date(Date.now() - 1000 * 60 * 100).toISOString(),
    new Date(Date.now() - 1000 * 60 * 90).toISOString(),
    mockVisits[0], mockPatients[0]
  ),
  makeInvoice(
    'inv2', 'v2', 'p2', `${format(new Date(), 'yy')}${format(new Date(), 'MM')}-0002`,
    [
      { id: 'li3', name: 'Consultation Fee', quantity: 1, amount: 300 },
      { id: 'li4', name: 'ECG', quantity: 1, amount: 150 },
    ],
    50, 'paid_online', 'online_upi',
    new Date(Date.now() - 1000 * 60 * 80).toISOString(),
    new Date(Date.now() - 1000 * 60 * 70).toISOString(),
    mockVisits[1], mockPatients[1]
  ),
  makeInvoice(
    'inv3', 'v3', 'p3', `${format(new Date(), 'yy')}${format(new Date(), 'MM')}-0003`,
    [
      { id: 'li5', name: 'Consultation Fee', quantity: 1, amount: 300 },
      { id: 'li6', name: 'ECG', quantity: 1, amount: 150 },
      { id: 'li7', name: 'X-Ray', quantity: 1, amount: 200 },
    ],
    0, 'pending', null,
    new Date(Date.now() - 1000 * 60 * 50).toISOString(),
    null,
    mockVisits[2], mockPatients[2]
  ),
  makeInvoice(
    'inv4', 'v4', 'p4', `${format(new Date(), 'yy')}${format(new Date(), 'MM')}-0004`,
    [
      { id: 'li8', name: 'Consultation Fee', quantity: 1, amount: 300 },
    ],
    0, 'pending', null,
    new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    null,
    mockVisits[3], mockPatients[3]
  ),
  makeInvoice(
    'inv7', 'v7', 'p7', `${format(subDays(new Date(), 1), 'yy')}${format(subDays(new Date(), 1), 'MM')}-0001`,
    [
      { id: 'li13', name: 'Consultation Fee', quantity: 1, amount: 300 },
      { id: 'li14', name: 'X-Ray', quantity: 1, amount: 200 },
    ],
    0, 'paid_cash', 'cash',
    subDays(new Date(), 1).toISOString(),
    subDays(new Date(), 1).toISOString(),
    mockVisits[6], mockPatients[6]
  ),
  makeInvoice(
    'inv8', 'v8', 'p8', `${format(subDays(new Date(), 1), 'yy')}${format(subDays(new Date(), 1), 'MM')}-0002`,
    [
      { id: 'li15', name: 'Consultation Fee', quantity: 1, amount: 300 },
      { id: 'li16', name: 'Urine Test', quantity: 1, amount: 60 },
    ],
    30, 'paid_online', 'online_upi',
    subDays(new Date(), 1).toISOString(),
    subDays(new Date(), 1).toISOString(),
    mockVisits[7], mockPatients[7]
  ),
]
